export enum IndicadorPresenca {
  NAO_SE_APLICA = 'NAO_SE_APLICA',
  PRESENCIAL = 'PRESENCIAL',
  INTERNET = 'INTERNET',
  TELEATENDIMENTO = 'TELEATENDIMENTO',
  NFCe_ENTREGA_DOMICILIO = 'NFCe_ENTREGA_DOMICILIO',
  NFCe_PRESENCIAL_FORA_ESTABELECIMENTO = 'NFCe_PRESENCIAL_FORA_ESTABELECIMENTO',
  OUTROS = 'OUTROS',
}

