export enum ModalidadeFrete {
  SEM_FRETE = 'SEM_FRETE',
  POR_CONTA_EMITENTE = 'POR_CONTA_EMITENTE',
  POR_CONTA_DESTINATARIO = 'POR_CONTA_DESTINATARIO',
  POR_CONTA_TERCEIROS = 'POR_CONTA_TERCEIROS',
}
