import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNewAreas1762059438764 implements MigrationInterface {
    name = 'AddNewAreas1762059438764'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "formas_pagamento" DROP CONSTRAINT "formas_pagamento_companyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP CONSTRAINT "FK_orcamentos_local_estoque"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP CONSTRAINT "FK_orcamentos_forma_pagamento"`);
        await queryRunner.query(`DROP INDEX "public"."idx_formas_pagamento_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_formas_pagamento_ativo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_formas_pagamento_padrao"`);
        await queryRunner.query(`DROP INDEX "public"."idx_locais_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orcamentos_forma_pagamento"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_orcamentos_local_estoque"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cf_fluxo_company_status"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP COLUMN "dataEntrega"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP COLUMN "numeroOrdemCompra"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" DROP COLUMN "estoque"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" DROP COLUMN "numeroOrdem"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" DROP COLUMN "codigoBeneficioFiscal"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "dataPrevisao"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "formaPagamento"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "estoque"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "totalPedido"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "numeroPedido"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "numeroNFe"`);
        await queryRunner.query(`ALTER TABLE "contas_financeiras" DROP COLUMN "saldo_atual"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD "numeroPedidoCotacao" character varying`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD "dataValidade" date`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" DROP COLUMN "descricao"`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ADD "descricao" character varying`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "ativo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "padrao" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ADD "nome" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ADD "codigo" character varying`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orcamento_itens" ALTER COLUMN "codigo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orcamento_itens" ALTER COLUMN "nome" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orcamento_itens" ALTER COLUMN "unidade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "quantidade" TYPE numeric(14,6)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "precoUnitario" TYPE numeric(14,6)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "descontoValor" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "freteRateado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "seguroRateado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "outrasDespesasRateado" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "totalItem" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" DROP COLUMN "numeroItem"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ADD "numeroItem" integer`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "consumidorFinal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "consumidorFinal" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "indicadorPresenca"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "indicadorPresenca" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "frete"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "frete" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "valorFrete" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "valorFrete" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "despesas" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "despesas" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "incluirFreteTotal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "incluirFreteTotal" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoLiquido" TYPE numeric(14,3)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoLiquido" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoBruto" TYPE numeric(14,3)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoBruto" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "volume" TYPE numeric(14,3)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "volume" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalProdutos" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalDescontos" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalImpostos" TYPE numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalGeral" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."status_pedido_venda_enum" RENAME TO "status_pedido_venda_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pedidos_venda_status_enum" AS ENUM('rascunho', 'pendente', 'em_preparacao', 'enviado', 'entregue', 'cancelado', 'faturado')`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "status" TYPE "public"."pedidos_venda_status_enum" USING "status"::"text"::"public"."pedidos_venda_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "status" SET DEFAULT 'rascunho'`);
        await queryRunner.query(`DROP TYPE "public"."status_pedido_venda_enum_old"`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ADD CONSTRAINT "FK_63fad9c2c9fb052226b04b95b20" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ADD CONSTRAINT "FK_834c2dcf9ba4adba9a722719eb9" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD CONSTRAINT "FK_16686a8b69415fe690ad0f2a7a0" FOREIGN KEY ("formaPagamentoId") REFERENCES "formas_pagamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD CONSTRAINT "FK_ebed09a5da4ef95b20776c7d7bd" FOREIGN KEY ("localEstoqueId") REFERENCES "locais_estoque"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD CONSTRAINT "FK_7088628a2505d8901608abb3b2b" FOREIGN KEY ("orcamentoId") REFERENCES "orcamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD CONSTRAINT "FK_4e61c35bc4cd5e3de6604cf6e31" FOREIGN KEY ("naturezaOperacaoPadraoId") REFERENCES "natureza_operacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD CONSTRAINT "FK_7b268b10e2820ae6446f709565b" FOREIGN KEY ("formaPagamentoId") REFERENCES "formas_pagamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD CONSTRAINT "FK_1d9029f3bed626f32858a999771" FOREIGN KEY ("localEstoqueId") REFERENCES "locais_estoque"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP CONSTRAINT "FK_1d9029f3bed626f32858a999771"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP CONSTRAINT "FK_7b268b10e2820ae6446f709565b"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP CONSTRAINT "FK_4e61c35bc4cd5e3de6604cf6e31"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP CONSTRAINT "FK_7088628a2505d8901608abb3b2b"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP CONSTRAINT "FK_ebed09a5da4ef95b20776c7d7bd"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP CONSTRAINT "FK_16686a8b69415fe690ad0f2a7a0"`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" DROP CONSTRAINT "FK_834c2dcf9ba4adba9a722719eb9"`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" DROP CONSTRAINT "FK_63fad9c2c9fb052226b04b95b20"`);
        await queryRunner.query(`CREATE TYPE "public"."status_pedido_venda_enum_old" AS ENUM('cancelado', 'em_preparacao', 'entregue', 'enviado', 'faturado', 'pendente', 'rascunho')`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "status" TYPE "public"."status_pedido_venda_enum_old" USING "status"::"text"::"public"."status_pedido_venda_enum_old"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "status" SET DEFAULT 'rascunho'`);
        await queryRunner.query(`DROP TYPE "public"."pedidos_venda_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."status_pedido_venda_enum_old" RENAME TO "status_pedido_venda_enum"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalGeral" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalImpostos" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalDescontos" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "totalProdutos" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "volume" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "volume" TYPE numeric(10,3)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoBruto" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoBruto" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoLiquido" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "pesoLiquido" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "incluirFreteTotal" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "incluirFreteTotal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "despesas" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "despesas" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "valorFrete" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "valorFrete" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "frete"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "frete" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" DROP COLUMN "indicadorPresenca"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "indicadorPresenca" integer NOT NULL DEFAULT '2'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "consumidorFinal" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ALTER COLUMN "consumidorFinal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" DROP COLUMN "numeroItem"`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ADD "numeroItem" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "totalItem" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "outrasDespesasRateado" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "seguroRateado" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "freteRateado" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "descontoValor" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "precoUnitario" TYPE numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ALTER COLUMN "quantidade" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "orcamento_itens" ALTER COLUMN "unidade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orcamento_itens" ALTER COLUMN "nome" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orcamento_itens" ALTER COLUMN "codigo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" DROP COLUMN "codigo"`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ADD "codigo" text`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "locais_estoque" ADD "nome" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "padrao" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ALTER COLUMN "ativo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" DROP COLUMN "descricao"`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ADD "descricao" text`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP COLUMN "dataValidade"`);
        await queryRunner.query(`ALTER TABLE "orcamentos" DROP COLUMN "numeroPedidoCotacao"`);
        await queryRunner.query(`ALTER TABLE "contas_financeiras" ADD "saldo_atual" numeric(15,2) DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "numeroNFe" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "numeroPedido" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "totalPedido" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "estoque" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "formaPagamento" integer NOT NULL DEFAULT '15'`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda" ADD "dataPrevisao" date`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ADD "codigoBeneficioFiscal" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ADD "numeroOrdem" character varying`);
        await queryRunner.query(`ALTER TABLE "pedidos_venda_itens" ADD "estoque" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD "numeroOrdemCompra" character varying`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD "dataEntrega" date`);
        await queryRunner.query(`CREATE INDEX "idx_cf_fluxo_company_status" ON "contas_financeiras" ("id", "companyId", "status") WHERE ((status)::text = 'ativo'::text)`);
        await queryRunner.query(`CREATE INDEX "IDX_orcamentos_local_estoque" ON "orcamentos" ("localEstoqueId") `);
        await queryRunner.query(`CREATE INDEX "IDX_orcamentos_forma_pagamento" ON "orcamentos" ("formaPagamentoId") `);
        await queryRunner.query(`CREATE INDEX "idx_locais_company" ON "locais_estoque" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "idx_formas_pagamento_padrao" ON "formas_pagamento" ("padrao") `);
        await queryRunner.query(`CREATE INDEX "idx_formas_pagamento_ativo" ON "formas_pagamento" ("ativo") `);
        await queryRunner.query(`CREATE INDEX "idx_formas_pagamento_company_id" ON "formas_pagamento" ("companyId") `);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD CONSTRAINT "FK_orcamentos_forma_pagamento" FOREIGN KEY ("formaPagamentoId") REFERENCES "formas_pagamento"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orcamentos" ADD CONSTRAINT "FK_orcamentos_local_estoque" FOREIGN KEY ("localEstoqueId") REFERENCES "locais_estoque"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formas_pagamento" ADD CONSTRAINT "formas_pagamento_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
